# Generated by Django 5.0.6 on 2024-08-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_home', '0005_usercompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
