# Generated by Django 5.0.7 on 2024-08-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customerrequest_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
    ]
