# Generated by Django 5.0.6 on 2024-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customerrequest_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
