# Generated by Django 5.0.7 on 2024-08-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_customerrequest_userrequest'),
        ('crm_home', '0008_remove_company_staff_userprofile_delete_companystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='mobile',
        )
    ]
