# Generated by Django 5.0.6 on 2024-08-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customerrequest_company'),
        ('crm_home', '0008_remove_company_staff_userprofile_delete_companystaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRequest',
            new_name='UserRequest',
        ),
    ]
