# Generated by Django 5.0.6 on 2024-08-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_userrequest_mobile_userrequest_company'),
        ('crm_home', '0008_remove_company_staff_userprofile_delete_companystaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
