# Generated by Django 5.0.6 on 2024-08-29 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userrequest_company_delete_user'),
        ('crm_home', '0008_remove_company_staff_userprofile_delete_companystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm_home.company'),
        ),
    ]
