# Generated by Django 5.0.6 on 2024-08-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_email_remove_appointment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
