# Generated by Django 5.0.6 on 2024-08-21 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
