# Generated by Django 5.0.6 on 2024-09-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_title'),
        ('customer', '0003_customer_company_customer_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
