# Generated by Django 5.0.6 on 2024-08-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due',
            new_name='due_Date',
        ),
    ]
