# Generated by Django 5.0.6 on 2024-08-21 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_due_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_Date',
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
