# Generated by Django 5.0.6 on 2024-09-02 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_company_customer_staff'),
        ('task', '0003_remove_task_due_date_task_due_time_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
