# Generated by Django 5.0.6 on 2024-09-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='client_name',
        ),
    ]
